### ISSUE TITLE
What about sdist?

### ISSUE THREAD

**Issue by pombredanne** [jwodder/wheel-filename#1]
Thank for this fine package. Any plan to support also sdist zip or tar.gz filenames?

**Comment by jwodder** [comment]
I do not have any plans to do so at this time.  For one thing, sdist filenames are not standardized and are also ambiguous (Which is the project and which is the version in `1-2-3.tar.gz`?).  Once both those issues are addressed, I may add support.

If you're truly in need of sdist filename parsing, try `parse_filename()` from my [`pypi-simple`](https://github.com/jwodder/pypi-simple) package.

**Comment by pombredanne** [comment]
@jwodder thanks!

@Abhishek-Dev09  please check this and https://github.com/jwodder/pypi-simple
IMHO, it would be best if you can contribute here rather than having your own code for that.
