### ISSUE TITLE
Add entry_point to run as cli

### ISSUE THREAD

**Issue by beenje** [jwodder/wheel-filename#2]
Hi!

I'd like to add a simple cli so that `wheel-filename pip-18.0-py2.py3-none-any.whl` would return the package info as json for example. It could be interested to use in scripts.

Would you be opened to such feature? If yes, I can create a PR.

**Comment by jwodder** [comment]
Good idea!  I went ahead and implemented this myself, and it's out now in version 1.4.0.

**Comment by beenje** [comment]
Thanks!
